version: '3.8'

services:
  backend:
    environment:
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    environment:
      ENV: production

  mysql:
    volumes:
      - mysql_prod_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    volumes:
      - redis_prod_data:/data

volumes:
  mysql_prod_data:
  redis_prod_data:
