# 使用官方的 Rust 镜像作为基础镜像
FROM rust:1.82

# 创建一个新的空目录，作为我们的工作空间
WORKDIR /usr/src/app

# 复制 Cargo.toml 和 Cargo.lock（如果存在），以便安装依赖
COPY Cargo.toml Cargo.lock ./

COPY . .

# 安装依赖，以便创建缓存层
RUN cargo fetch

# 安装开发工具，例如 curl 以及 cargo-watch
RUN apt-get update && apt-get install -y curl \
    && cargo install cargo-watch

# 默认命令
CMD ["cargo", "watch", "-x", "run"]
